### ISSUE TITLE
Djinn menu does not appear in combat under certain circumstances

### ISSUE THREAD

**Issue by Karanum** [Karanum/gs2-randomiser2#24]
This issue is possibly related to summon cost shuffling.

**Comment by Karanum** [comment]
Reported by MDarkGuard to occur on chaos preset, seed 5154121060891239, with auto-run and increased coin scaling

**Comment by XerShade** [comment]
I'm pretty sure it's a vanilla game mechanic being messed with because of the shuffling. I think it's the same mechanic that stops you from seeing the Djinni menus in Sol Sanctum and The pre-game because the devs assumed you'd HAVE to have at least one summon if you have on Djinni. I'd look there to start. 

One way to test this if possible, purposely set a summon to 0 Djinni and start a new game and get out of Daila with cheats or something so you can get into combat with no Djinni but a summon that has 0 requirements. Would also test if we can do 0 requirement summons or not and how badly the game would freak if we used them.
