### ISSUE TITLE
Archipelago Multiworld Randomizer Support

### ISSUE THREAD

**Issue by Teanji** [Karanum/gs2-randomiser2#33]
Archipelago has recently updated its Discord to include a Forum for Future Game Design collaboration.
I recently saw a new development for Lufia II being integrated, and given the puzzles, was reminded again of GS:TLA.

It would be
- Artifacts (Unique Items) in Shops as Checks / Items for other games.
- Djinni / Summon Tablets / Treasure Chests as Checks / Items for other games.
- Gambling Rewards as Checks (might be a 'Hard' option given the nature of the RNG -- albeit manipulatable in GS).
- Forgeable Rewards as Checks (again, possible 'Hard' option given RNG of rewards).
- Psynergy Rock Rewards (ie. Parch / Reveal) as Checks / Items for other games.
- Gold Shirt / Boots / Ring Checks from the first game carrier over as Multiworld Checks for other games.
- Trading Quest (very much a 'Hard' option given the randomness between multiple games).
-- Would likely need to start the game with a Password entered for GS1 Djinni / Psynergy items.
-- Few of the togglable options on the randomzier such as Retreat / Avoid costing 0, and starting with them.
-- Unlocked Ship / Secret Dungeons (Iris) by default might be recommended.

Development Discord (apologies if you don't want links on this Github):
https://discord.com/invite/8Z65BR2

Suggested Game Additions Tracker for Archipelago :
https://docs.google.com/spreadsheets/d/1HZvn4wSjb633Uxu2o8oHambwP0aAax4XnADidn3xs3g/edit#gid=450876694

**Comment by Karanum** [comment]
While I've addressed this before on Discord, since I've been cleaning out the issue tracker I want to just make a formal notice here as well.

AP multiworld support for this randomiser is not something I will pursue within the foreseeable future. It would require the full randomiser code to be ported to Python, along with various additions to allow for custom items, as well as hooking into the game's event queue so items can be received. It's just too much when the main randomiser still has several big features I want to work on, including its own multiworld mode sometime.

That being said, I changed the repository license a while back which allows anyone who wants to tackle this project to do so. I'm also willing to offer help on Discord to anyone seriously attempting this.
